L = {"L_open": {'EN':"Open",'FR':"Ouvrir"},
    "L_refresh":{'EN':"Refresh",'FR':"Rafraichir"},
    "L_Coeff":{'EN':"Coefficient",'FR':"Coefficient"},
    "L_if":{'EN':"If",'FR':"Si"},
    "L_column":{'EN':"column",'FR':"colonne"},
    "L_operator":{'EN':"operator",'FR':"opérateur"},
    "L_ref_value":{'EN':"reference value",'FR':"valeur référence"},
    "L_then":{'EN':"then",'FR':"alors"},
    "L_direction":{'EN':"direction",'FR':"direction"},
    "L_score_of":{'EN':"score by",'FR':"score de"},
    "L_score_value":{'EN':"Score value",'FR':"valeur score"},
    "L_remove":{'EN':"Remove",'FR':"Supprimer"},
    "L_save_as":{'EN':"Save as...",'FR':"Enregistrer sous..."},
    "L_text":{'EN':"text files",'FR':"fichiers texte"},
    "L_all":{'EN':"all files",'FR':"tous les fichiers"},
    "L_export_as":{'EN':"Export as...",'FR':"Exporter sous..."},
    "L_browse":{'EN':"Browse",'FR':"Parcourir"},
    "L_csv":{'EN':"csv files",'FR':"fichiers csv"},
    "L_data_param":{'EN':"Data parameters",'FR':"Paramètres de données"},
    "L_separator":{'EN':"Separator : ",'FR':"Séparateur : "},
    "L_header":{'EN':"There is a header",'FR':"Présence d'un entête"},
    "L_jump_lines":{'EN':"Number of lines to jump",'FR':"Nombre de lignes à sauter"},
    "L_try":{'EN':"Try",'FR':"Essayer"},
    "L_save":{'EN':"Save",'FR':"Enregistrer"},
    "L_name":{'EN':"my soft name",'FR':"ajouter un nom ici"},
    "L_welcome":{'EN':"Welcome",'FR':"Bienvenue"},
    "L_foot":{'EN':"This is a footer",'FR':"Ceci est un pied de page"},
    "L_load_data":{'EN':"Load data",'FR':"Charger des données"},
    "L_export":{'EN':"Export",'FR':"Export"},
    "L_load_rules":{'EN':"Load rules",'FR':"Charger des règles"},
    "L_undo":{'EN':"Undo",'FR':"Annuler"},
    "L_quit":{'EN':"Quit",'FR':"Quitter"},
    "L_file":{'EN':"File",'FR':"Fichier"},
    "L_edit":{'EN':"Edit",'FR':"Edition"},
    "L_add_1":{'EN':"Add 1 line",'FR':"Ajouter 1 ligne"},
    "L_add_3":{'EN':"Add 3 lines",'FR':"Ajouter 3 lignes"},
    "L_add_5":{'EN':"Add 5 lines",'FR':"Ajouter 5 lignes"},
    "L_print_increasing":{'EN':"sort increasing",'FR':"Tri croissant"},
    "L_print_decreasing":{'EN':"sort decreasing",'FR':"Tri décroissant"},
    "L_parameters":{'EN':"Parameters",'FR':"Paramètres"},
    "L_opening_parameters":{'EN':"Opening parameters",'FR':"Paramètres d'ouverture"},
    "Contains":{'EN':"Contains",'FR':"contient"},
    "Don't contains":{'EN':"Don't contains",'FR':"ne contient pas"},
    "Increase":{'EN':"Increase",'FR':"Augmenter"},
    "Decrease":{'EN':"Decrease",'FR':"Diminuer"},
    "L_no_visual":{'EN':"No visual mode",'FR':"Mode non visuel"},
    "Browse save":{'EN':"Browse saves",'FR':"Parcourir les sauvegardes"},
    "Browse data":{'EN':"Browse data", 'FR':"Parcourir les données"},
    "L_variant":{'EN':"variant files",'FR':"Fichier variant"},
    "L_multiple_files":{'EN':"Choose files",'FR':"Choisissez des fichiers"},
    "L_go":{'EN':"Go !",'FR':"Lancer !"},
    "multiple":{'EN':"Multiple",'FR':"Multiple"},
    "add_multiple":{'EN':"Add multiple",'FR':"Ajouter multiple"},
    "L_all_multiple":{'EN':"All the lines below are true", 'FR':"Toutes les lignes ci dessous sont vraies"},
    "L_add_condition":{'EN':"Add condition",'FR':"Ajouter une condition"},
    "next_colonne":{'EN':"Print Next columns", 'FR':"Afficher les colonnes suivantes"},
    "lang_label":{'EN':"Language",'FR':"Langage"},
    "mode_fenetre":{'EN':"Windows use",'FR':"Mode de fenêtre"},
    "mode_fenetre_on":{'EN':"Use different windows",'FR':"Utiliser plusieurs fenêtres"},
    "quit":{'EN':"Quit",'FR':"Quitter"},
    "Do you want to quit?":{'EN':"Do you want to quit?",'FR':"Voulez vous vraiment quitter ?"}
}
